TEST_GEN_PROGS := timens timerfd timer clock_nanosleep procfs exec futex \
	vfork_exec offsets_size_ppps
TEST_GEN_PROGS_EXTENDED := gettime_perf

CFLAGS := -Wall -Werror -pthread
LDLIBS := -lrt -ldl

include ../lib.mk
