# SPDX-License-Identifier: GPL-2.0

TEST_GEN_PROGS := drm_gem_mmap_ppps ttm_vm_fault_ppps
TEST_PROGS := drm_mm.sh i915.sh drm_gem_mmap_ppps.sh ttm_vm_fault_ppps.sh
TEST_FILES := ../../ppps/ppps_run_module.sh
TEST_GEN_MODS_DIR := ppps_modules

include ../../lib.mk
