# SPDX-License-Identifier: GPL-2.0-only
CFLAGS += $(KHDR_INCLUDES) -I../../../../include
LDFLAGS += -static

TEST_GEN_PROGS := wrapfd wrapfd_mmap_ppps

top_srcdir ?=../../../../..

include ../../lib.mk
