# SPDX-License-Identifier: GPL-2.0
all:

TEST_PROGS := zram.sh
TEST_GEN_PROGS_EXTENDED := zram_process_range_ppps
TEST_FILES := zram01.sh zram02.sh zram_lib.sh
EXTRA_CLEAN := err.log

include ../lib.mk
