/* SPDX-License-Identifier: GPL-2.0 */
#ifndef __FOLIO_WITHIN_RANGE_PPPS_H
#define __FOLIO_WITHIN_RANGE_PPPS_H

#include <linux/ioctl.h>

#define FOLIO_WITHIN_RANGE_PPPS_CHECK_ALIGNED _IO('f', 1)
#define FOLIO_WITHIN_RANGE_PPPS_CHECK_SUBPAGE _IO('f', 2)
#define FOLIO_WITHIN_RANGE_PPPS_CHECK_ADDRESS_END _IO('f', 3)

#endif /* __FOLIO_WITHIN_RANGE_PPPS_H */
