/* SPDX-License-Identifier: GPL-2.0 */
#ifndef SG_PAGE_SLICES_PPPS_H
#define SG_PAGE_SLICES_PPPS_H

#include <linux/ioctl.h>

enum sg_page_slices_case {
	SG_SLICES_FULL_PAGE,
	SG_SLICES_PARTIAL_PAGE,
	SG_SLICES_CONTIGUOUS,
	SG_SLICES_REORDERED,
	SG_SLICES_DISTINCT_PAGES,
	SG_SLICES_OVERLAPPING,
	SG_SLICES_CHAINED,
	SG_SLICES_EMPTY_ARRAY,
	SG_SLICES_EMPTY_SIZE,
	SG_SLICES_NULL_PAGE,
	SG_SLICES_ZERO_LENGTH,
	SG_SLICES_INVALID_OFFSET,
	SG_SLICES_PAGE_OVERRUN,
	SG_SLICES_SIZE_TOO_SMALL,
	SG_SLICES_SIZE_TOO_LARGE,
	SG_SLICES_HUGE_LENGTH,
	SG_SLICES_CASES,
};

#define SG_PAGE_SLICES_PPPS_CHECK _IO('S', 0x73)
#endif
