# SPDX-License-Identifier: GPL-2.0-only
CFLAGS += $(KHDR_INCLUDES)

TEST_GEN_PROGS := udmabuf
TEST_GEN_FILES := udmabuf_ppps
TEST_PROGS := udmabuf_ppps.sh
TEST_FILES := ../../ppps/ppps_run_module.sh

TEST_GEN_MODS_DIR := ppps_modules

top_srcdir ?=../../../../..

include ../../lib.mk
