# SPDX-License-Identifier: GPL-2.0-only
CFLAGS += $(KHDR_INCLUDES)

TEST_GEN_PROGS := udmabuf
TEST_GEN_FILES := udmabuf_ppps
TEST_PROGS := udmabuf_ppps.sh

TEST_GEN_MODS_DIR := dmabuf_mmap_ppps_module

top_srcdir ?=../../../../..

include ../../lib.mk
